### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by sunhay** [itajenglish/Fix-My-Mood#1]
Hi!

Looks like this public repository has the SoundCloud intern challenge API keys hardcoded in plaintext. Mind removing this repository from GitHub for now? We'd like to make sure the key doesn't get leaked and abused.

Thanks,
Sunny

**Comment by itajenglish** [comment]
Hi @sunhay ,

Sorry, completely didn't realize I didn't put it in env file. I'll remove it right away!
